import type { OrganizationRole } from '../organization/organization.types';
import { PERMISSIONS, type Permission } from './permission.types';

export const ROLE_PERMISSIONS: Record<OrganizationRole, readonly Permission[]> =
  {
    OWNER: [
      PERMISSIONS.APPROVAL_VIEW,
      PERMISSIONS.APPROVAL_REQUEST,
      PERMISSIONS.APPROVAL_APPROVE,
      PERMISSIONS.APPROVAL_REJECT,
      PERMISSIONS.APPROVAL_CANCEL,
    ],

    ADMIN: [
      PERMISSIONS.APPROVAL_VIEW,
      PERMISSIONS.APPROVAL_REQUEST,
      PERMISSIONS.APPROVAL_APPROVE,
      PERMISSIONS.APPROVAL_REJECT,
      PERMISSIONS.APPROVAL_CANCEL,
    ],

    AGENT: [
      PERMISSIONS.APPROVAL_VIEW,
      PERMISSIONS.APPROVAL_REQUEST,
      PERMISSIONS.APPROVAL_APPROVE,
      PERMISSIONS.APPROVAL_REJECT,
      PERMISSIONS.APPROVAL_CANCEL,
    ],

    REQUESTER: [PERMISSIONS.APPROVAL_VIEW],
  };
